// <auto-generated />
namespace SignalRDemoDataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Subjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Subjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201307210110072_Subjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
